name: Deploy to EC2
on:
  push:
    branches:
      - main

env:
  PROJECT: "bolhadev-chat"
  DOCKER_REPO: "brunoroh/bolhadev-chat"
  DOCKER_USERNAME: "brunoroh"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: brunoroh/bolhadev-chat:latest

      - name: SSH into EC2 instance and deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.MY_EC2_SSH_KEY }}
          script: |
            sudo docker pull ${{ env.DOCKER_REPO }}:latest
            sudo docker stop my-node-app || true
            sudo docker rm my-node-app || true
            sudo docker run -d -p 3000:3000 --name my-node-app ${{ env.DOCKER_REPO }}:latest
